#!/usr/bin/env bash
# Seed one latest-insight row per ticker into the platform table, and create a confirmed
# Cognito test user in the `readers` group (required for GET /insights/*).
source "$(dirname "$0")/lib/common.sh"
load_state
: "${TEST_USER_PASSWORD:?TEST_USER_PASSWORD must be set (generated by run-all)}"
[[ -n "${USER_POOL_ID:-}" ]] || die "USER_POOL_ID not in state (run deploy first)"

GEN_AT="2026-07-11T10:00:00Z"
for t in "${TICKERS[@]}"; do
  log "Seeding insight for $t"
  item=$(jq -n --arg pk "TICKER#$t" --arg sk "INSIGHT#$GEN_AT" --arg gen "$GEN_AT" '{
    PK:{S:$pk}, SK:{S:$sk}, generatedAt:{S:$gen},
    signal:{S:"BULLISH"}, confidence:{N:"0.82"},
    rationale:{S:"Seeded load-test insight for '"$t"'"},
    drivers:{L:[{S:"momentum"},{S:"volume"}]},
    source:{S:"loadtest-seed"}, insightText:{S:"Synthetic insight for load testing."},
    modelId:{S:"seed"}}')
  run aws dynamodb put-item --table-name "$TABLE" --item "$item"
done

log "Creating test user $TEST_USER (idempotent: Security pool is retained across runs)"
# admin-create-user fails if the user already exists in the retained pool; tolerate that and reuse.
# set-password and add-to-group below are idempotent, so a reused user is fully reset each run.
run aws cognito-idp admin-create-user --user-pool-id "$USER_POOL_ID" \
  --username "$TEST_USER" --message-action SUPPRESS \
  --user-attributes Name=email,Value="$TEST_USER" Name=email_verified,Value=true \
  || log "test user already exists in retained pool, reusing"
run aws cognito-idp admin-set-user-password --user-pool-id "$USER_POOL_ID" \
  --username "$TEST_USER" --password "$TEST_USER_PASSWORD" --permanent
run aws cognito-idp admin-add-user-to-group --user-pool-id "$USER_POOL_ID" \
  --username "$TEST_USER" --group-name readers
log "Seed complete: ${#TICKERS[@]} insights + test user in readers"
